[package]
name = "lattice-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lattice"
path = "src/main.rs"

[dependencies]
lattice    = { path = "../lattice" }
lspd-client = { git = "https://github.com/anibalanto/lspd.git", branch = "main" }
anyhow     = "1"
clap       = { version = "4", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
